// <auto-generated />
namespace MarketApplication.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class satici_ekleme : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(satici_ekleme));
        
        string IMigrationMetadata.Id
        {
            get { return "202206291827335_satici_ekleme"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
